import XCTest
@testable import ResearchOSFlightRecorder

@MainActor
final class PublicationPersistenceTests: XCTestCase {
    private func directory() -> URL {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("PublicationPersistenceTests-\(UUID())", isDirectory: true)
        addTeardownBlock { try? FileManager.default.removeItem(at: url) }
        return url
    }

    private func store() -> ResearchWorkspaceStore {
        ResearchWorkspaceStore(projects: [], storageDirectory: directory())
    }

    private func project(in store: ResearchWorkspaceStore) throws -> UUID {
        try XCTUnwrap(store.createProject(title: "Publication persistence fixture", question: "Does the canonical record survive style and storage changes?"))
    }

    private func manuscript() -> PublicationManuscript {
        var value = PublicationManuscript(id: UUID(uuidString: "A8DF1840-EA34-4892-A831-99739EC17D61")!, title: "Synthetic persistence fixture: café, μ and 12.75")
        value.abstract = "An automated storage fixture. No human or provider outcome is represented."
        value.authors = [.init(id: "author-one", name: "Fixture Author", affiliationIDs: ["affiliation-one"])]
        value.affiliations = [.init(id: "affiliation-one", label: "Synthetic test institution")]
        value.sections = [.init(id: "section-one", role: .results, heading: "Results retained literally", blocks: [
            .init(id: "paragraph-one", text: "Observed value 12.75; this fixture asserts persistence, not validity.", citationIDs: ["reference-one"], evidenceLinks: [.init(sourceID: "source-one", sourceVersion: "version-1", evidenceID: "evidence-one", locator: "page 2, paragraph 3", url: "https://example.com/fixture")]),
            .init(id: "equation-one", kind: .equation, text: "E = mc^2; α = 0.05"),
            .init(id: "table-one", kind: .table, text: "Raw observations", caption: "Synthetic test values", table: .init(columns: ["Group", "Value"], rows: [["A", "12.75"], ["B", "9.00"]]))
        ])]
        value.references = [.init(id: "reference-one", title: "Synthetic storage reference", authors: ["Fixture Author"], year: 2026)]
        value.unknownFields = ["funding"]
        value.authorDecisions = ["annotation-status": "Automated fixture, no human validation"]
        return value
    }

    func testHistoricalPrePublicationArchiveReplaysAndExportsIdenticalBytes() throws {
        // Frozen first event from the September 21 native handoff, not generated by
        // this implementation. Metadata head is the retained event's original head.
        let legacy = Data(Self.historicalArchive.utf8)
        XCTAssertFalse(Self.historicalArchive.contains("\"publication\""))
        let target = store()
        let id = try target.importArchiveData(legacy)
        XCTAssertEqual(id.uuidString.lowercased(), "1a23376d-b264-4e01-af68-2fae237df45c")
        XCTAssertNil(target.project(id: id)?.publication)
        XCTAssertEqual(try target.exportArchiveData(id: id), legacy)
        let relaunched = ResearchWorkspaceStore(projects: [], storageDirectory: try XCTUnwrap(target.storageDirectoryURL))
        XCTAssertNil(relaunched.persistenceFailure)
        XCTAssertEqual(try relaunched.exportArchiveData(id: id), legacy)
        XCTAssertEqual(try relaunched.eventHistory(projectID: id).first?.chainDigest, "4dba348b04536f026bfa6f4a4fd99ba6dca40cd4d1aa64003ffb431e9f928f4b")
    }

    func testPublicationSaveIncrementsRevisionAndPreservesPastSnapshots() throws {
        let target = store(), original = manuscript()
        let id = try project(in: target)
        try target.savePublication(projectID: id, manuscript: original, expectedRevision: nil)
        let journal = try XCTUnwrap(target.storageDirectoryURL).appendingPathComponent("events-v1.jsonl")
        let firstJournal = try Data(contentsOf: journal)
        var edited = try XCTUnwrap(target.project(id: id)?.publication)
        XCTAssertEqual(edited.revision, 1)
        edited.title = "Explicit author revision 2"
        edited.sections[0].blocks[0].text = "Author changed 12.75 to 13.25; prior text remains in history."
        try target.savePublication(projectID: id, manuscript: edited, expectedRevision: 1)
        let latest = try XCTUnwrap(target.project(id: id)?.publication)
        XCTAssertEqual(latest.id, original.id)
        XCTAssertEqual(latest.revision, 2)
        XCTAssertEqual(latest.title, "Explicit author revision 2")
        XCTAssertTrue(try Data(contentsOf: journal).starts(with: firstJournal))
        XCTAssertNil(try target.project(id: id, throughSequence: 1)?.publication)
        XCTAssertEqual(try target.project(id: id, throughSequence: 2)?.publication, original)
        XCTAssertEqual(try target.project(id: id, throughSequence: 3)?.publication, latest)
        XCTAssertEqual(try target.eventHistory(projectID: id).map(\.kind), ["project.created", "publication.saved", "publication.saved"])
        let relaunched = ResearchWorkspaceStore(projects: [], storageDirectory: try XCTUnwrap(target.storageDirectoryURL))
        XCTAssertNil(relaunched.persistenceFailure)
        XCTAssertEqual(relaunched.project(id: id)?.publication, latest)
        XCTAssertEqual(try relaunched.project(id: id, throughSequence: 2)?.publication, original)
    }

    func testDiscardedEditorAndProfileRenderingLeaveStoredScienceAndArchiveUnchanged() throws {
        let target = store(), original = manuscript()
        let id = try project(in: target)
        try target.savePublication(projectID: id, manuscript: original, expectedRevision: nil)
        let archive = try target.exportArchiveData(id: id)
        var unsavedDraft = try XCTUnwrap(target.project(id: id)?.publication)
        unsavedDraft.title = "Canceled edit"
        unsavedDraft.sections[0].blocks.removeAll()
        // Cancel discards this value; there is deliberately no store Save command.
        XCTAssertNotEqual(unsavedDraft, original)
        let a = try XCTUnwrap(PublicationProfile.registry.first { $0.id == "plos-one-research" })
        let b = try XCTUnwrap(PublicationProfile.registry.first { $0.id == "iclr-2027-initial" })
        let first = try PublicationEngine.preflight(original, profile: a)
        _ = try PublicationEngine.preflight(original, profile: b)
        XCTAssertEqual(try PublicationEngine.preflight(original, profile: a), first)
        let renderedA = try PublicationRenderer.render(original, profile: a)
        let renderedB = try PublicationRenderer.render(original, profile: b)
        let renderedAgain = try PublicationRenderer.render(original, profile: a)
        XCTAssertEqual(renderedA.canonical, try original.canonicalData())
        XCTAssertEqual(renderedB.canonical, renderedA.canonical)
        XCTAssertEqual(renderedAgain.canonical, renderedA.canonical)
        XCTAssertEqual(renderedAgain.html, renderedA.html)
        XCTAssertEqual(renderedA.receipt.manuscriptRevision, 1)
        XCTAssertEqual(target.project(id: id)?.publication, original)
        XCTAssertEqual(try target.exportArchiveData(id: id), archive)
    }

    func testStaleEditorAndReplacementIdentityCannotOverwriteSavedRevision() throws {
        let target = store(), original = manuscript()
        let id = try project(in: target)
        try target.savePublication(projectID: id, manuscript: original, expectedRevision: nil)
        var current = original
        current.title = "Newer author decision"
        try target.savePublication(projectID: id, manuscript: current, expectedRevision: 1)
        let before = try target.exportArchiveData(id: id)
        var stale = original
        stale.title = "Stale editor must not win"
        XCTAssertThrowsError(try target.savePublication(projectID: id, manuscript: stale, expectedRevision: 1))
        var replacement = try XCTUnwrap(target.project(id: id)?.publication)
        replacement.id = UUID()
        XCTAssertThrowsError(try target.savePublication(projectID: id, manuscript: replacement, expectedRevision: 2))
        XCTAssertEqual(try target.exportArchiveData(id: id), before)
        XCTAssertEqual(target.project(id: id)?.publication?.title, "Newer author decision")
        XCTAssertEqual(target.project(id: id)?.publication?.revision, 2)
    }

    func testFailedAtomicPublicationAppendKeepsOriginalJournalAndProjection() throws {
        var failWrites = false
        let target = ResearchWorkspaceStore(projects: [], storageDirectory: directory(), atomicAppendWriter: { data, url in
            if failWrites { throw NSError(domain: "PublicationPersistenceTests.InjectedWriteFailure", code: 1) }
            try data.write(to: url, options: [.atomic, .completeFileProtection])
        })
        let id = try project(in: target), original = manuscript()
        try target.savePublication(projectID: id, manuscript: original, expectedRevision: nil)
        let journal = try XCTUnwrap(target.storageDirectoryURL).appendingPathComponent("events-v1.jsonl")
        let before = try Data(contentsOf: journal)
        var changed = original
        changed.title = "This write must fail"
        failWrites = true
        XCTAssertThrowsError(try target.savePublication(projectID: id, manuscript: changed, expectedRevision: 1))
        XCTAssertEqual(try Data(contentsOf: journal), before)
        XCTAssertEqual(target.project(id: id)?.publication, original)
        let relaunched = ResearchWorkspaceStore(projects: [], storageDirectory: try XCTUnwrap(target.storageDirectoryURL))
        XCTAssertNil(relaunched.persistenceFailure)
        XCTAssertEqual(relaunched.project(id: id)?.publication, original)
        XCTAssertEqual(try relaunched.eventHistory(projectID: id).count, 2)
    }

    func testNearTwentyMBPublicationRejectsAllSnapshotAppendsWithoutLosingPortableHistory() throws {
        let target = store(), id = try project(in: target)
        var original = manuscript()
        // Canonical bound is 12 MB. One 10.6 MB manuscript event fits the 20 MB
        // portable-history bound; any second full project snapshot cannot fit.
        // No renderer/image allocation is involved in this storage-only test.
        original.abstract = String(repeating: "a", count: 10_600_000)
        try target.savePublication(projectID: id, manuscript: original, expectedRevision: nil)
        let committed = try XCTUnwrap(target.project(id: id)), archive = try target.exportArchiveData(id: id)
        XCTAssertGreaterThan(archive.count, 10_000_000)
        XCTAssertLessThanOrEqual(archive.count, ResearchArgumentLimits.maximumArchiveBytes)
        let history = try target.eventHistory(projectID: id)

        target.renameProject(id: id, to: "This rename would make the archive too large")
        XCTAssertNil(target.persistenceFailure, "Capacity rejection is not corrupt history and must not hide all projects.")
        XCTAssertEqual(target.project(id: id), committed)
        XCTAssertEqual(try target.exportArchiveData(id: id), archive)

        target.updateProject(id: id) { $0.scope.question = "A scope edit also duplicates the full manuscript." }
        // A capacity error may be surfaced by the synchronous flush, but it must
        // restore the committed projection and keep every earlier event intact.
        do { try target.flushPendingChanges() } catch { }
        XCTAssertNil(target.persistenceFailure)
        XCTAssertEqual(target.project(id: id), committed)
        XCTAssertEqual(try target.exportArchiveData(id: id), archive)

        target.archiveProject(id: id)
        XCTAssertNil(target.persistenceFailure)
        XCTAssertEqual(target.project(id: id), committed)
        XCTAssertEqual(try target.eventHistory(projectID: id), history)
        XCTAssertEqual(try target.exportArchiveData(id: id), archive)

        let imported = store()
        XCTAssertEqual(try imported.importArchiveData(archive), id)
        XCTAssertEqual(imported.project(id: id)?.publication, original)
        XCTAssertEqual(try imported.exportArchiveData(id: id), archive)
    }

    func testGeneralProjectEditorCannotInjectRewriteOrErasePublication() throws {
        let target = store(), original = manuscript()
        let id = try project(in: target)
        let emptyArchive = try target.exportArchiveData(id: id)
        target.updateProject(id: id) { $0.publication = original }
        try target.flushPendingChanges()
        XCTAssertNil(target.project(id: id)?.publication)
        XCTAssertNotNil(target.mutationAccessFailure)
        XCTAssertEqual(try target.exportArchiveData(id: id), emptyArchive)
        try target.savePublication(projectID: id, manuscript: original, expectedRevision: nil)
        let archive = try target.exportArchiveData(id: id)
        target.updateProject(id: id) { $0.publication?.title = "Forged generic-editor rewrite" }
        target.updateProject(id: id) { $0.publication = nil }
        try target.flushPendingChanges()
        XCTAssertEqual(target.project(id: id)?.publication, original)
        XCTAssertEqual(try target.exportArchiveData(id: id), archive)
        XCTAssertNotNil(target.mutationAccessFailure)
    }

    func testPublicationArchiveRoundTripPreservesRelationshipsAndCanonicalBytes() throws {
        let source = store(), original = manuscript()
        let id = try project(in: source)
        try source.savePublication(projectID: id, manuscript: original, expectedRevision: nil)
        let archive = try source.exportArchiveData(id: id)
        let target = store()
        XCTAssertEqual(try target.importArchiveData(archive), id)
        let imported = try XCTUnwrap(target.project(id: id)?.publication)
        XCTAssertEqual(try imported.canonicalData(), try original.canonicalData())
        XCTAssertEqual(imported.sections[0].blocks[0].citationIDs, ["reference-one"])
        XCTAssertEqual(imported.sections[0].blocks[0].evidenceLinks.first?.sourceVersion, "version-1")
        XCTAssertEqual(imported.sections[0].blocks[1].text, "E = mc^2; α = 0.05")
        XCTAssertEqual(imported.sections[0].blocks[2].table?.rows, [["A", "12.75"], ["B", "9.00"]])
        XCTAssertEqual(try target.exportArchiveData(id: id), archive)
    }

    func testDowngradeRetainsAdditionalProjectManuscriptAndExportsButBlocksNewSave() throws {
        let target = store()
        // Isolated application-state contract fixture, not a provider transaction.
        target.updateSubscriptionAccess(.plusActive(expirationDate: nil))
        let first = try XCTUnwrap(target.createProject(title: "First", question: "Free slot", subscriptionState: .plusActive(expirationDate: nil)))
        let second = try XCTUnwrap(target.createProject(title: "Second", question: "Retained after downgrade", subscriptionState: .plusActive(expirationDate: nil)))
        for id in [first, second] { try target.savePublication(projectID: id, manuscript: manuscript(), expectedRevision: nil) }
        target.updateSubscriptionAccess(.free)
        let readOnly = try XCTUnwrap([first, second].first { !target.canMutateProject(id: $0) })
        let original = try XCTUnwrap(target.project(id: readOnly)?.publication)
        let archive = try target.exportArchiveData(id: readOnly)
        var edit = original
        edit.title = "Unavailable mutation after downgrade"
        XCTAssertThrowsError(try target.savePublication(projectID: readOnly, manuscript: edit, expectedRevision: 1))
        XCTAssertEqual(target.project(id: readOnly)?.publication, original)
        XCTAssertEqual(try target.exportArchiveData(id: readOnly), archive)
        XCTAssertTrue(FileManager.default.fileExists(atPath: try target.exportProjectFile(id: readOnly).path))
        let relaunched = ResearchWorkspaceStore(projects: [], storageDirectory: try XCTUnwrap(target.storageDirectoryURL))
        XCTAssertFalse(relaunched.canMutateProject(id: readOnly))
        XCTAssertEqual(relaunched.project(id: readOnly)?.publication, original)
        XCTAssertEqual(try relaunched.exportArchiveData(id: readOnly), archive)
        let reimported = store()
        XCTAssertEqual(try reimported.importArchiveData(archive), readOnly)
        XCTAssertEqual(reimported.project(id: readOnly)?.publication, original)
    }

    func testHashCorrectCreationCannotSmugglePublicationIntoLegacyCommand() throws {
        let source = store()
        let id = try project(in: source)
        let original = try XCTUnwrap(source.eventHistory(projectID: id).first)
        var payload = try XCTUnwrap(JSONSerialization.jsonObject(with: CanonicalJSON.encode(original.payload)) as? [String: Any])
        var mutations = try XCTUnwrap(payload["mutations"] as? [[String: Any]])
        var value = try XCTUnwrap(mutations[0]["value"] as? [String: Any])
        value["publication"] = try JSONSerialization.jsonObject(with: manuscript().canonicalData())
        mutations[0]["value"] = value
        payload["mutations"] = mutations
        let forged = try ResearchEventDraft(eventID: original.eventID, projectID: original.projectID, branchID: "main", kind: original.kind, actorRef: "human:local", authorityRef: "role:owner", origin: "ios:local", idempotencyKey: original.idempotencyKey, occurredAt: original.occurredAt, priorProjectDigest: ResearchOSSchema.zeroDigest, resultProjectDigest: CanonicalJSON.digest(CanonicalJSONValue(jsonObject: value)), payload: CanonicalJSONValue(jsonObject: payload), objectRefs: original.objectRefs)
        let forgedStore = try ResearchEventStore(rootDirectory: directory())
        _ = try forgedStore.append(forged)
        XCTAssertTrue(forgedStore.audit().valid) // Hash consistency alone is not command authority.
        let target = store()
        XCTAssertThrowsError(try target.importArchiveData(forgedStore.exportArchive(projectID: original.projectID)))
        XCTAssertTrue(target.projects.isEmpty)
        XCTAssertNil(target.persistenceFailure)
    }

    // Source full archive SHA-256: c57e3c35bcb404cb34d93573a90586adfda8a2267b1057c3a609367d31d0680b
    // Retained original event payload/chain/result digests; canonical one-event archive.
    private static let historicalArchive = #"""
    {"events":[{"actor_ref":"human:local","authority_ref":"role:owner","branch_id":"main","cause_refs":[],"chain_digest":"4dba348b04536f026bfa6f4a4fd99ba6dca40cd4d1aa64003ffb431e9f928f4b","event_id":"event-b3f76031-15ae-4f33-804e-3d6e9ff7ad2c","idempotency_key":"command-b3f76031-15ae-4f33-804e-3d6e9ff7ad2c","kind":"project.created","object_refs":[{"logical_id":"1a23376d-b264-4e01-af68-2fae237df45c","object_type":"project","project_id":"1a23376d-b264-4e01-af68-2fae237df45c","version":1}],"occurred_at":"2026-09-21T02:25:51.186Z","origin":"ios:local","parent_event_ids":[],"payload":{"classification":"SYNTHETIC_DEMO_ONLY","command":"project.created","mutations":[{"depends_on":[],"operation":"put","ref":{"logical_id":"1a23376d-b264-4e01-af68-2fae237df45c","object_type":"project","project_id":"1a23376d-b264-4e01-af68-2fae237df45c","version":1},"value":{"claims":[],"classification":"SYNTHETIC_DEMO_ONLY","createdAt":"2026-09-21T02:25:51.186Z","defense":[{"evidencePointer":"","id":"04508CD2-9C5C-4C56-9685-657FF4656E65","objection":"What would change your conclusion?","response":""},{"evidencePointer":"","id":"047476F8-237A-4952-9D59-9DFA8FA24222","objection":"Where could selection or measurement bias enter?","response":""}],"fileSystem":[{"id":"5D31FA2E-DE51-4357-A6B8-919C78BF1E64","path":"00-scope/","purpose":"Question, population, variables, exclusions","status":"Derived at display time"},{"id":"FEED91BF-9C2C-46BF-B2EF-22198ABE7699","path":"01-protocol/","purpose":"Frozen method and disclosed amendments","status":"Derived at display time"},{"id":"2CE5C02D-ED77-4E35-B16F-EBDADAE8E9FE","path":"02-inputs/","purpose":"Source inventory and integrity notes","status":"Derived at display time"},{"id":"070EF200-5ED2-45F8-BF08-CEB1CADDFB65","path":"03-analysis/","purpose":"Executable methods and environment","status":"Derived at display time"},{"id":"D4DF1C0A-1AD7-416A-9C08-5BAD143D21B9","path":"04-claims/","purpose":"Claim-to-evidence map and limitations","status":"Derived at display time"},{"id":"714440F1-BEB7-4E28-A23B-E84685BCD302","path":"05-defense/","purpose":"Objections, responses, unresolved risks","status":"Derived at display time"},{"id":"3E5E05CA-879D-4A28-946D-CA24A270DBA6","path":"06-release/","purpose":"Human-approved export; never silent publication","status":"Derived at display time"}],"id":"1A23376D-B264-4E01-AF68-2FAE237DF45C","inbox":[],"protocolRecord":{"changePolicy":"","frozenByHuman":false,"method":"","primaryOutcome":""},"repairs":[],"reproducibility":[{"detail":"List every source, file, and inclusion boundary.","id":"4D1686B5-F9AC-4071-8207-BFAFDEF9198C","state":"open","title":"Inputs identified"},{"detail":"Document steps, versions, parameters, and seeds where applicable.","id":"A55F0304-6973-4261-A222-BEAE6D8AA6C8","state":"open","title":"Method executable"},{"detail":"Connect each reported output to its generating step.","id":"B30EC0D6-3743-470E-8A2E-47738F55179C","state":"open","title":"Outputs mapped"},{"detail":"Record only a rerun actually performed by another environment or person.","id":"851CDCC0-141B-4C23-9EFC-29B28F782CAC","state":"open","title":"Independent rerun"}],"scope":{"exclusions":"","population":"","question":"How did recall differ in this invented classroom sample?","variables":""},"status":"active","title":"Music and recall — synthetic sample","updatedAt":"2026-09-21T02:25:51.186Z"}}],"tombstone":false,"workflow_stage":"REVIEW","workspace_schema_id":"com.challa.research-os.mobile.workspace-command","workspace_schema_version":1},"payload_digest":"5330d98ec466831da4bea91ef8ec3b2142ecb08cf65a01554c8d32c1658a6ff6","prior_project_digest":"0000000000000000000000000000000000000000000000000000000000000000","project_id":"1a23376d-b264-4e01-af68-2fae237df45c","result_project_digest":"e865efc2a28e321aa50daa0a1b6698deb57f7748a1a71e5ea926a421c7833321","schema_id":"com.challa.research-os.event","schema_version":1,"sequence":1}],"exported_head_digest":"4dba348b04536f026bfa6f4a4fd99ba6dca40cd4d1aa64003ffb431e9f928f4b","project_id":"1a23376d-b264-4e01-af68-2fae237df45c","schema_id":"com.challa.research-os.mobile.event-archive","schema_version":1}
    """#
}
